# Generated by Django 4.2.2 on 2023-06-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("author", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("genre", models.CharField(max_length=40)),
                ("publication_date", models.DateField()),
                (
                    "authors",
                    models.ManyToManyField(related_name="book", to="author.author"),
                ),
            ],
        ),
    ]
