# Generated by Django 4.2.2 on 2023-06-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("author", "0002_alter_author_id"),
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="authors",
            field=models.ManyToManyField(
                null=True, related_name="book", to="author.author"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
