# Generated by Django 4.2.2 on 2023-07-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0002_alter_book_authors_alter_book_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="book",
            name="price",
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
