# Generated by Django 4.2.2 on 2023-07-19 23:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2023, 7, 19, 23, 35, 36, 3058, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
    ]
