# Generated by Django 4.2.2 on 2023-07-15 13:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0002_alter_order_books"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="books",
        ),
    ]
