# Generated by Django 4.2.2 on 2023-07-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0003_book_count_book_price"),
        ("order", "0003_remove_order_books"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="books",
            field=models.ManyToManyField(through="order.OrderItem", to="book.book"),
        ),
    ]
