# Generated by Django 4.2.2 on 2023-07-17 21:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0004_order_books"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 18, 0, 39, 25, 310367)
            ),
        ),
    ]
