# Generated by Django 4.2.2 on 2023-07-19 23:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0006_alter_order_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.IntegerField(null=True),
        ),
    ]
