# Generated by Django 4.2.2 on 2023-07-19 16:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0007_monosettings_alter_order_created_at"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MonoSettings",
        ),
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 19, 19, 40, 5, 80119)
            ),
        ),
    ]
