# Generated by Django 4.2.2 on 2023-07-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0007_alter_orderitem_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="pay_url",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
